include( "${CMAKE_CURRENT_LIST_DIR}/compression_valence/compression_valence.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/curvature/curvature.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/decompression_valence/decompression_valence.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/jnd/jnd.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/msdm2/msdm2.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/processing/processing.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/scaling/scaling.cmake" )
